# Generated by Django 3.1.7 on 2021-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('URL', models.CharField(max_length=50)),
                ('published', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
