# Generated by Django 3.1.7 on 2021-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
