# Generated by Django 3.1.7 on 2021-05-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_auto_20210327_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='content',
            new_name='ganre',
        ),
        migrations.AlterField(
            model_name='list',
            name='URL',
            field=models.CharField(max_length=100),
        ),
    ]
